# Numpy vs Python list

In [1]:
import numpy as np

In [20]:
lstArray = range(1000000)
nArray = np.arange(1000000)

lstArray
nArray

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [28]:
%time for i in range(0, 10): result = [x*2 for x in lstArray]

Wall time: 1.61 s


In [25]:
%time for j in range(0, 10): result2 = nArray*2

Wall time: 105 ms


In [32]:
x = np.zeros((4,5))

In [33]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
y = np.ones((4,4))

In [35]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
z = np.empty((2,5))

In [37]:
z

array([[1.09992511e-311, 2.27270197e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307],
       [1.16096346e-028, 1.04857803e-142, 1.16467185e-028,
        9.62872377e+199, 1.25536825e-071]])

In [38]:
lst = [2,5, 6,9,10, 110]
nplst = np.array(lst)

In [39]:
nplst

array([  2,   5,   6,   9,  10, 110])

In [52]:
aa = np.arange(1,1000, 5)

In [53]:
ashape = aa.shape

In [54]:
ashape

(200,)

In [58]:
aa.reshape((8,5,5))

array([[[  1,   6,  11,  16,  21],
        [ 26,  31,  36,  41,  46],
        [ 51,  56,  61,  66,  71],
        [ 76,  81,  86,  91,  96],
        [101, 106, 111, 116, 121]],

       [[126, 131, 136, 141, 146],
        [151, 156, 161, 166, 171],
        [176, 181, 186, 191, 196],
        [201, 206, 211, 216, 221],
        [226, 231, 236, 241, 246]],

       [[251, 256, 261, 266, 271],
        [276, 281, 286, 291, 296],
        [301, 306, 311, 316, 321],
        [326, 331, 336, 341, 346],
        [351, 356, 361, 366, 371]],

       [[376, 381, 386, 391, 396],
        [401, 406, 411, 416, 421],
        [426, 431, 436, 441, 446],
        [451, 456, 461, 466, 471],
        [476, 481, 486, 491, 496]],

       [[501, 506, 511, 516, 521],
        [526, 531, 536, 541, 546],
        [551, 556, 561, 566, 571],
        [576, 581, 586, 591, 596],
        [601, 606, 611, 616, 621]],

       [[626, 631, 636, 641, 646],
        [651, 656, 661, 666, 671],
        [676, 681, 686, 691, 696],
        [7

In [59]:
a = np.random.randn(10)

In [60]:
a

array([-0.96952247,  2.16429716,  0.06357599, -0.36901544, -0.1452843 ,
       -0.06764731, -0.39574994,  0.86020012,  1.20598562,  1.20935324])

In [64]:
b = np.random.randn(10)

In [65]:
b

array([ 0.77839382,  0.64644253, -0.59033424, -0.32898685,  1.07684128,
       -0.48843564, -0.32435927,  0.33257378, -0.53248338,  2.36021101])

In [66]:
a + b

array([-0.19112865,  2.81073969, -0.52675825, -0.6980023 ,  0.93155699,
       -0.55608295, -0.7201092 ,  1.1927739 ,  0.67350224,  3.56956424])

In [67]:
a * b

array([-0.75467031,  1.39909373, -0.03753109,  0.12140123, -0.15644813,
        0.03304136,  0.12836516,  0.28608   , -0.64216729,  2.85432882])

In [68]:
a/b

array([-1.24554235,  3.34801171, -0.10769491,  1.12167231, -0.13491709,
        0.13849789,  1.22009751,  2.58649408, -2.26483241,  0.512392  ])

In [72]:
a>1

array([False,  True, False, False, False, False, False, False,  True,
        True])

In [73]:
a[a>1]

array([2.16429716, 1.20598562, 1.20935324])

# Numpy boolean and fancy indexing

In [74]:
arr1 = np.array([2,5,9,10,11,25])

In [75]:
arr1[1]

5

In [77]:
arr1[arr1 >= 10]

array([10, 11, 25])

In [82]:
arr1[arr1 < 5]

array([2])

In [83]:
arr1[[5,2,1]]

array([25,  9,  5])

In [85]:
arr2 = np.random.randn(10,10)

In [86]:
arr2

array([[-0.71742328, -0.16599259,  0.90882736,  0.58950936, -0.49318183,
        -0.25905644,  0.98514289,  0.51428944,  1.60127414, -0.33270191],
       [-0.97918853,  1.38465024,  0.29066596, -1.3213697 , -1.00024339,
        -0.92706519,  1.95487712,  1.51019636, -2.24980973,  1.46459354],
       [ 0.61738809,  0.76180335, -0.90030938,  0.77963497, -0.96389334,
         0.02331097,  0.11354875,  0.32319396,  0.57579523,  0.02095648],
       [ 0.63039547, -1.03220526,  0.57627451,  1.97552858, -0.41359414,
         0.33051667,  0.01019887,  0.10252342, -0.68774382,  0.86862081],
       [-0.46792422,  0.50402946, -0.48998129,  1.0190452 ,  2.53911925,
         1.21483096, -1.19245457, -0.51922229, -0.67125758, -0.74752093],
       [ 0.57531702,  0.06422153,  0.46278043,  0.64707889,  0.09135163,
         0.44211756, -0.24394407, -0.47409951,  2.37723566,  0.2526824 ],
       [ 0.18733922,  1.10104042, -0.98020469,  1.01873552,  0.07359128,
        -0.13803766, -1.79022402, -0.24719141

In [88]:
arr2[0][7]

0.5142894408419747

In [91]:
arr2[0:10:2]

array([[-0.71742328, -0.16599259,  0.90882736,  0.58950936, -0.49318183,
        -0.25905644,  0.98514289,  0.51428944,  1.60127414, -0.33270191],
       [ 0.61738809,  0.76180335, -0.90030938,  0.77963497, -0.96389334,
         0.02331097,  0.11354875,  0.32319396,  0.57579523,  0.02095648],
       [-0.46792422,  0.50402946, -0.48998129,  1.0190452 ,  2.53911925,
         1.21483096, -1.19245457, -0.51922229, -0.67125758, -0.74752093],
       [ 0.18733922,  1.10104042, -0.98020469,  1.01873552,  0.07359128,
        -0.13803766, -1.79022402, -0.24719141, -0.49338212,  2.04404622],
       [-0.17193451,  0.23220402, -0.89110381,  0.24787585, -0.73273348,
        -0.2464153 , -0.15162214,  2.15279482,  0.12939134, -0.28930633]])

In [92]:
arr2[0:10:1,2:10:2]

array([[ 0.90882736, -0.49318183,  0.98514289,  1.60127414],
       [ 0.29066596, -1.00024339,  1.95487712, -2.24980973],
       [-0.90030938, -0.96389334,  0.11354875,  0.57579523],
       [ 0.57627451, -0.41359414,  0.01019887, -0.68774382],
       [-0.48998129,  2.53911925, -1.19245457, -0.67125758],
       [ 0.46278043,  0.09135163, -0.24394407,  2.37723566],
       [-0.98020469,  0.07359128, -1.79022402, -0.49338212],
       [ 0.71851222, -0.60668018,  1.75041245,  1.074841  ],
       [-0.89110381, -0.73273348, -0.15162214,  0.12939134],
       [ 0.3103267 , -0.51325614,  0.15769261, -0.50954683]])

In [95]:
arr3 = np.ones((10,5))

In [96]:
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
arr3[1:-1,1:-1] = 0

In [105]:
arr3

array([[1., 9., 9., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Numpy basic functions

In [7]:
x = [2,5,49,81,15,325]
np.sqrt(x)

array([ 1.41421356,  2.23606798,  7.        ,  9.        ,  3.87298335,
       18.02775638])

In [8]:
x2 = [2, 5, 11, 25, 16]
np.square(x2)

array([  4,  25, 121, 625, 256], dtype=int32)

In [10]:
y = [4,3,45,82,16,300]
np.maximum(x,y)

array([  4,   5,  49,  82,  16, 325])

In [11]:
np.max(x)

325

# Numpy Where Function

In [13]:
lstSalary = np.array([900000, 100000, 0, -2, -1, 20000000, 2500000])
np.where(lstSalary <= 0, 21000, lstSalary)

array([  900000,   100000,    21000,    21000,    21000, 20000000,
        2500000])

In [14]:
np.where(lstSalary <= 0, "Invaid Salary", "Valid Salary")

array(['Valid Salary', 'Valid Salary', 'Invaid Salary', 'Invaid Salary',
       'Invaid Salary', 'Valid Salary', 'Valid Salary'], dtype='<U13')

In [16]:
x = np.array([5,7, 9, 11,12])

In [17]:
x.sum()

44

In [34]:
x[x>5]

array([11, 12, 17, 19])

In [18]:
y = x>5

In [19]:
y

array([False,  True,  True,  True,  True])

In [20]:
y.any()

True

In [21]:
y.sum()

4

In [22]:
y.all()

False

In [23]:
x.sort()

In [25]:
x = np.array([5,17, 19, 11,12])

In [27]:
x.sort()

In [28]:
x

array([ 5, 11, 12, 17, 19])

In [33]:
np.unique(x)

array([ 5, 11, 12, 17, 19])

In [36]:
aa = np.array([1,22,25,10,26])

In [37]:
bb = np.array([2,20,7,9,10,11])

In [38]:
np.save("aaFile",aa)

In [41]:
loadaa = np.load("aaFile.npy","r")

In [42]:
loadaa

memmap([ 1, 22, 25, 10, 26])

In [46]:
np.savez("abFile",aa,bb)

In [49]:
abLoad = np.load("abFile.npz")

In [61]:
abLoad['arr_0']

array([ 1, 22, 25, 10, 26])

In [65]:
for key,value in abLoad.items():
    for val in value:
        print(key, val)

arr_0 1
arr_0 22
arr_0 25
arr_0 10
arr_0 26
arr_1 2
arr_1 20
arr_1 7
arr_1 9
arr_1 10
arr_1 11


# Numpy Linear Algebra Function

In [66]:
x = np.random.randn(2,3)

In [67]:
y = np.random.randn(3,2)

In [68]:
x.dot(y)

array([[ 2.08215597, -1.37832545],
       [-0.54750666,  0.85593039]])

In [69]:
x.transpose()

array([[-0.09546253,  0.8214309 ],
       [-0.92442394,  0.61326906],
       [-0.82680103,  0.83504183]])

In [70]:
x.trace()

0.5178065267993164

In [74]:
x.take(4)

0.61326905711023

# Numpy Reshape Function

In [2]:
import numpy as np

In [3]:
x = np.random.randn(4,5)

In [4]:
x

array([[-1.21287736,  0.3159206 ,  0.12800328,  0.8727031 , -0.41911811],
       [ 0.3594641 , -0.29011071, -0.16640817, -0.72081515,  1.85955132],
       [-1.57791341,  0.58721915, -0.14359275, -0.15964578, -0.04551525],
       [-0.33174238,  0.46541096, -0.7409767 , -1.25540748, -1.70439027]])

In [5]:
x.reshape(5,4)

array([[-1.21287736,  0.3159206 ,  0.12800328,  0.8727031 ],
       [-0.41911811,  0.3594641 , -0.29011071, -0.16640817],
       [-0.72081515,  1.85955132, -1.57791341,  0.58721915],
       [-0.14359275, -0.15964578, -0.04551525, -0.33174238],
       [ 0.46541096, -0.7409767 , -1.25540748, -1.70439027]])

In [12]:
x = x.reshape(2,5,2)

In [13]:
x

array([[[-1.21287736,  0.3159206 ],
        [ 0.12800328,  0.8727031 ],
        [-0.41911811,  0.3594641 ],
        [-0.29011071, -0.16640817],
        [-0.72081515,  1.85955132]],

       [[-1.57791341,  0.58721915],
        [-0.14359275, -0.15964578],
        [-0.04551525, -0.33174238],
        [ 0.46541096, -0.7409767 ],
        [-1.25540748, -1.70439027]]])

In [14]:
xx = x.reshape(2,5,2, order = 'F')

In [15]:
xx

array([[[-1.21287736,  0.3159206 ],
        [ 0.12800328,  0.8727031 ],
        [-0.41911811,  0.3594641 ],
        [-0.29011071, -0.16640817],
        [-0.72081515,  1.85955132]],

       [[-1.57791341,  0.58721915],
        [-0.14359275, -0.15964578],
        [-0.04551525, -0.33174238],
        [ 0.46541096, -0.7409767 ],
        [-1.25540748, -1.70439027]]])

In [19]:
x3 = xx.reshape(-1,2,5)

In [20]:
x3.ravel()

array([-1.21287736,  0.3159206 ,  0.12800328,  0.8727031 , -0.41911811,
        0.3594641 , -0.29011071, -0.16640817, -0.72081515,  1.85955132,
       -1.57791341,  0.58721915, -0.14359275, -0.15964578, -0.04551525,
       -0.33174238,  0.46541096, -0.7409767 , -1.25540748, -1.70439027])

In [21]:
x3.flatten()

array([-1.21287736,  0.3159206 ,  0.12800328,  0.8727031 , -0.41911811,
        0.3594641 , -0.29011071, -0.16640817, -0.72081515,  1.85955132,
       -1.57791341,  0.58721915, -0.14359275, -0.15964578, -0.04551525,
       -0.33174238,  0.46541096, -0.7409767 , -1.25540748, -1.70439027])

# Numpy Concatenate, vstack, hstack and Split Functions

In [22]:
import numpy as np

In [24]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [25]:
arr2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

In [28]:
np.concatenate((arr1,arr2), axis = 0 )

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
np.concatenate((arr1,arr2), axis = 1 )

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [32]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [74]:
aar3 = [1,2,4,5,6,7,8,9]

In [75]:
np.array(aar3)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [76]:
aar4 = [11,12,14,15,16,17,18,19]

In [77]:
np.array(aar4)

array([11, 12, 14, 15, 16, 17, 18, 19])

In [80]:
np.split(aar3,[2,4])

[array([1, 2]), array([4, 5]), array([6, 7, 8, 9])]

In [82]:
 x4 = [aar3,aar4]

In [86]:
x5 = np.split(x4, [3,6], axis=1)

In [88]:
x5.count

<function list.count(value, /)>

# Numpy Repeat and Tile Functions

In [96]:
x = [[1,2,4,5]]

In [100]:
np.repeat(x,3,axis = 1)

array([[1, 1, 1, 2, 2, 2, 4, 4, 4, 5, 5, 5]])

In [108]:
np.tile(x,5)

array([[1, 2, 4, 5, 1, 2, 4, 5, 1, 2, 4, 5, 1, 2, 4, 5, 1, 2, 4, 5]])