# Pandas Series

In [1]:
import pandas as pd

In [5]:
sobj = pd.Series([1,4,-3,2, "a"])

In [7]:
print(sobj)

0     1
1     4
2    -3
3     2
4     a
dtype: object


In [8]:
print(sobj.index, sobj.values)

RangeIndex(start=0, stop=5, step=1) [1 4 -3 2 'a']


In [9]:
sales = pd.Series([25000, 25000, 25000, 30000, 30000, 30000])

In [10]:
sales.value_counts()

30000    3
25000    3
dtype: int64

In [12]:
sales.values

array([25000, 25000, 25000, 30000, 30000, 30000], dtype=int64)

In [13]:
print(sales.values, sales.index)

[25000 25000 25000 30000 30000 30000] RangeIndex(start=0, stop=6, step=1)


In [23]:
sales = pd.Series([25000, 25000, 25000, 30000, 30000, 30000], ['Jan', 'Feb','Mar','Apr', 'May', 'Jun'], name="6 Months Sales")

In [25]:
print(sales)

Jan    25000
Feb    25000
Mar    25000
Apr    30000
May    30000
Jun    30000
Name: 6 Months Sales, dtype: int64


In [24]:
print(sales.index, sales.values)

Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], dtype='object') [25000 25000 25000 30000 30000 30000]


In [21]:
print(sales)

Jan    25000
Feb    25000
Mar    25000
Apr    30000
May    30000
Jun    30000
dtype: int64


In [22]:
print(sales.values)

[25000 25000 25000 30000 30000 30000]


In [30]:
swSales = [10, 15, 20, 25, 65,12, 100]
swIndexes = ['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday']
Name = "One Week Sandwitch Sales"


In [34]:
swSales = pd.Series(data = swSales, index=swIndexes, name=Name)

In [35]:
print(swSales)

Saturday      10
Sunday        15
Monday        20
Tuesday       25
Wednesday     65
Thursday      12
Friday       100
Name: One Week Sandwitch Sales, dtype: int64


In [36]:
print(swSales[1])

15


In [37]:
print(swSales["Sunday"])

15


In [38]:
print(swSales[[1,3,5]])

Sunday      15
Tuesday     25
Thursday    12
Name: One Week Sandwitch Sales, dtype: int64


In [39]:
print(swSales[["Monday","Friday",'Sunday']])

Monday     20
Friday    100
Sunday     15
Name: One Week Sandwitch Sales, dtype: int64


In [46]:
print(swSales[swSales > 5])

Saturday      10
Sunday        15
Monday        20
Tuesday       25
Wednesday     65
Thursday      12
Friday       100
Name: One Week Sandwitch Sales, dtype: int64


In [47]:
print(swSales[swSales.values > 5])

Saturday      10
Sunday        15
Monday        20
Tuesday       25
Wednesday     65
Thursday      12
Friday       100
Name: One Week Sandwitch Sales, dtype: int64


In [48]:
swSales = swSales*3

In [49]:
print(swSales)

Saturday      30
Sunday        45
Monday        60
Tuesday       75
Wednesday    195
Thursday      36
Friday       300
Name: One Week Sandwitch Sales, dtype: int64


In [54]:
swSales = swSales/3

In [55]:
print(swSales)

Saturday      3.333333
Sunday        5.000000
Monday        6.666667
Tuesday       8.333333
Wednesday    21.666667
Thursday      4.000000
Friday       33.333333
Name: One Week Sandwitch Sales, dtype: float64


In [79]:
import numpy as np
swSales = np.array([10, 15, 20, 25, 65,12, 100])
swIndexes = ['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday']
Name = "One Week Sandwitch Sales"
swSales = pd.Series(data = swSales, index=swIndexes, name=Name)
swSales.index = ['S','S','M','T','W','T','F']

In [80]:
print(swSales)

S     10
S     15
M     20
T     25
W     65
T     12
F    100
Name: One Week Sandwitch Sales, dtype: int32


In [84]:
sDicData = {"Punjab":14000000, "Sindh":3500000, "KPK":25000000, "Balochistan":12500000}
sIndexes = ["KPK",'Punjab','Sindh','Balochistan','Gilgitbulkistan']
DicName = "Population Of States in Pakistan"
state_population = pd.Series(data=sDicData, index=sIndexes, name=DicName)
state_population.index.name ="States Index Name"
#state_population.name = 'States Statistics'
print(state_population)

States Index Name
KPK                25000000.0
Punjab             14000000.0
Sindh               3500000.0
Balochistan        12500000.0
Gilgitbulkistan           NaN
Name: Population Of States in Pakistan, dtype: float64


In [66]:
print(state_population['KPK'])

25000000


In [67]:
print(state_population[['Punjab','Sindh']])

Punjab    14000000
Sindh      3500000
Name: Population Of States in Pakistan, dtype: int64


In [77]:
print(pd.isna(state_population))
print(state_population.isnull())

KPK                False
Punjab             False
Sindh              False
Balochistan        False
Gilgitbulkistan     True
Name: Population Of States in Pakistan, dtype: bool
KPK                False
Punjab             False
Sindh              False
Balochistan        False
Gilgitbulkistan     True
Name: Population Of States in Pakistan, dtype: bool


**Source of Data in Series**
* Direct data into series
* Data from Python List and Numpy Array
* Python Dictionery

In [254]:
data_df = pd.DataFrame(np.arange(16).reshape(4,4), columns = ['one','two','three','four'], 
                       index=['Texas','Ohio','Calorado','New York'])
print(data_df.loc[['Calorado','Ohio'],['one','three']])

          one  three
Calorado    8     10
Ohio        4      6


In [263]:
print(data_df)
#print(data_df.iloc[[2,3],[0,3]])
print(data_df.iloc[:2,:3])

          one  two  three  four
Texas       0    1      2     3
Ohio        4    5      6     7
Calorado    8    9     10    11
New York   12   13     14    15
       one  two  three
Texas    0    1      2
Ohio     4    5      6


In [275]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape(4,5), columns=list('abcde'))
#print(df1,'\n\n', df2)
print(df1+df2)
df3 = df1.add(df2, fill_value = 0)
print(df3)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [272]:
#df3.fillna

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [290]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns=list('abcd'))
series = pd.Series(data = [1,2,3,4] ,index=list('abcd'))
print(series.index, series.values)
print(df1-series)

Index(['a', 'b', 'c', 'd'], dtype='object') [1 2 3 4]
   a  b  c  d
0 -1 -1 -1 -1
1  3  3  3  3
2  7  7  7  7


In [298]:
#df1.drop(labels='a', axis=1, inplace=True)
data_df1 = df1.drop(index=0, axis=0)
data_df1

b   c   d
1  5   6   7
2  9  10  11

# Reindexing

In [306]:
obj3 = pd.Series(data = ['Yellow','Green','Blue'], index=[0,3,5])
obj3.reindex(range(8), method='ffill')
obj3.reindex(range(2,12),method='ffill')

2     Yellow
3      Green
4      Green
5       Blue
6       Blue
7       Blue
8       Blue
9       Blue
10      Blue
11      Blue
dtype: object

In [337]:
df_data2 = pd.DataFrame(data=np.arange(9).reshape(3,3), columns=['Texas','Utah','California'], index=['a','c','d'])
#df_states = df_data2.reindex(['a','b','c','d'], method='ffill')
#df_states = df_data2.reindex(columns = ['Ohio','California','Texas','New York'], method='ffill')
states = ['Texas','Utah','California','New York']
df_data2.sort_index(axis=1).reindex(columns=sorted(states))


California  New York  Texas  Utah
a           2       NaN      0     1
c           5       NaN      3     4
d           8       NaN      6     7

In [360]:
df_data2.Texas[df_data2.Utah>=1]

a    0
c    3
d    6
Name: Texas, dtype: int32

In [352]:
print(df_data2[df_data2.Utah>1])

   Texas  Utah  California
c      3     4           5
d      6     7           8


In [356]:
df_data2.iloc[1:,:2]

Texas  Utah
c      3     4
d      6     7

In [364]:
df_data2.loc[['a','d'],['Texas','Utah']]

Texas  Utah
a      0     1
d      6     7