In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,14,15,18,19])

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19])

In [4]:
a.datatype

AttributeError: 'numpy.ndarray' object has no attribute 'datatype'

In [5]:
a.shape

(16,)

In [6]:
a.reshape(2,4)

ValueError: cannot reshape array of size 16 into shape (2,4)

In [7]:
a.reshape((1,2))

ValueError: cannot reshape array of size 16 into shape (1,2)

In [8]:
a.reshape((2,19))

ValueError: cannot reshape array of size 16 into shape (2,19)

In [9]:
a.reshape((1,16))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19]])

In [10]:
a.reshape((2,16))

ValueError: cannot reshape array of size 16 into shape (2,16)

In [11]:
a.reshape((16,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [14],
       [15],
       [18],
       [19]])

In [12]:
a.reshape((2,3,4))

ValueError: cannot reshape array of size 16 into shape (2,3,4)

In [13]:
a.reshape((2,4,4))

ValueError: cannot reshape array of size 16 into shape (2,4,4)

In [14]:
a.reshape((2,3,2))

ValueError: cannot reshape array of size 16 into shape (2,3,2)

In [15]:
a.reshape((2,8,1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [14],
        [15],
        [18],
        [19]]])

In [16]:
a.reshape((4,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[14, 15],
        [18, 19]]])

In [17]:
a.reshape((16,1,1))

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[14]],

       [[15]],

       [[18]],

       [[19]]])

In [18]:
a.reshape((4,4,1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[14],
        [15],
        [18],
        [19]]])

In [19]:
a.rang(25)

AttributeError: 'numpy.ndarray' object has no attribute 'rang'

In [20]:
np.rang(25)

AttributeError: module 'numpy' has no attribute 'rang'

In [21]:
np.rang(10)

AttributeError: module 'numpy' has no attribute 'rang'

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19])

In [23]:
a.range

AttributeError: 'numpy.ndarray' object has no attribute 'range'

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19])

In [26]:
np.randint(100)

AttributeError: module 'numpy' has no attribute 'randint'

In [27]:
np.rand()

AttributeError: module 'numpy' has no attribute 'rand'

In [28]:
np.random()

TypeError: 'module' object is not callable

In [29]:
from numpy as random

SyntaxError: invalid syntax (<ipython-input-29-ee69bca6af19>, line 1)

In [30]:
from numpy import random


In [31]:
random.randint(100)

47

In [32]:
random.rand()


0.08848148287357283

In [33]:
import numpy as np


In [34]:
np.random(100)

TypeError: 'module' object is not callable

In [35]:
np.array(1,2,3,3.5)

ValueError: only 2 non-keyword arguments accepted

In [36]:
a = np.array([1,1.3,3])

a

In [38]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
c = np.raange(57)

AttributeError: module 'numpy' has no attribute 'raange'

In [40]:
c = np.arange(60)

In [41]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [42]:
c[1:50]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
c[-2]

58