In [1]:
import numpy as np


In [2]:
a = np.array([])

In [3]:
a = 10

In [4]:
a

10

In [6]:
counter = print("Enter any number to enqueue");

a = np.array({})

Enter any number to enqueue


In [7]:
a.argmax

<function ndarray.argmax>

In [8]:
a.max = 10

AttributeError: 'numpy.ndarray' object attribute 'max' is read-only

In [9]:
a.max

<function ndarray.max>

In [10]:
a.size

1

In [11]:
a = np.array([0,0,0,0,0,0,0,0,0])

In [12]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
a.size

9

In [14]:
counter = a.size;

In [15]:
counter

9

In [20]:
counter = a.size;

In [21]:
counter

9

In [23]:
if (counter == 0)
    print (a);
    pinter("Queue is empty");

else
    del a[counter];
    counter --;


SyntaxError: invalid syntax (<ipython-input-23-b9c99735c574>, line 1)

In [24]:
lst = np.array([4,5,3,1,2])


In [25]:
lst

array([4, 5, 3, 1, 2])

array([5, 3, 1, 2])

In [28]:
lst2.push(6)

AttributeError: 'numpy.ndarray' object has no attribute 'push'

In [29]:
lst2.push(lst.size, 6)

AttributeError: 'numpy.ndarray' object has no attribute 'push'

In [30]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
lst = []
lst.append(5)

In [36]:
lst

[5]

In [42]:
lst.append(8)
lst.append(4)
lst.append(3)
lst.append(4)
lst.append(5)


lst

[5, 8, 4, 3, 4, 5]

In [43]:
print(lst.pop())
print(lst.pop())

5
4


In [44]:
lst

[5, 8, 4, 3]

In [52]:
arr1 = np.array([{1,2,3,8,9,11},{2,5,11,89}])
arr1

array([{1, 2, 3, 8, 9, 11}, {89, 2, 11, 5}], dtype=object)

In [48]:
arr1.size

2

In [49]:
arr1[0]

{1, 2, 3, 8, 9}

In [50]:
arr1[1]

{2, 5, 11, 89}

In [51]:
arr1

array([{1, 2, 3, 8, 9}, {89, 2, 11, 5}], dtype=object)

In [53]:
arr1

array([{1, 2, 3, 8, 9, 11}, {89, 2, 11, 5}], dtype=object)

In [54]:
import pandas as pd


In [55]:
a = pd.Series(arr1)

In [56]:
a

0    {1, 2, 3, 8, 9, 11}
1         {89, 2, 11, 5}
dtype: object

In [57]:
a = [1,2,4,8,99]
a = pd.Series(a)

In [58]:
a

0     1
1     2
2     4
3     8
4    99
dtype: int64

In [59]:
pd.DataFrame(a)

0
0   1
1   2
2   4
3   8
4  99

In [65]:
lst = {"Name":["Safdar","Ali"],"Age":["25","35"], "Gender":["Male","Female"]}
pd.DataFrame(lst)

Name Age  Gender
0  Safdar  25    Male
1     Ali  35  Female